services:
  flask:
    build: ./flask
    container_name: flask_dashboard
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mediamtx

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always
    ports:
      - "8554:8554"   # RTSP
      - "8889:8889"   # Web UI + WebRTC
      - "8888:8888"   # HLS
      - "8189:8189"   # WebRTC (UDP/TCP)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    command: /mediamtx.yml
