services:
  flask:
    build: ./flask
    container_name: flask_dashboard
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mediamtx

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: always

    ports:
      - "127.0.0.1:8889:8889"   # WebRTC (nginx proxy)
      - "127.0.0.1:9997:9997"   # API (flask)
      - "8554:8554"             # RTSP push

    volumes:
      - ./mediamtx.yml:/mediamtx.yml

    command: mediamtx /mediamtx.yml
